version: '3'

services:
  web_app:
    container_name: web_app
    build: .
    volumes:
      - .:/src
    restart: always
    expose:
      - "8000"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web_app

  certbot:
    # Новый контейнер, который запуститься вместе с nginx
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    command: certbot certonly --webroot --webroot-path /var/www/certbot/ -d labao.ru
