version: '3'

services:
  web_app:
    container_name: test_app
    build: .
    volumes:
      - .:/src
      - StaticVolumeTestApp:/example_project/static
    expose:
      - 8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000

volumes:
  StaticVolumeTestApp: